#!/bin/sh

num=$(light)
bright=$(printf '%.0f\n' $num) 

case 1 in
	$((bright >= 80)) ) icon=" " ;;
	$((bright >= 60)) ) icon=" " ;;
	$((bright >= 40)) )  icon=" " ;;
	$((bright >= 0)) )  icon=" " ;;
	* ) echo  && exit ;;
esac

echo "$icon $bright%"
