#!/bin/sh

vol=$(pamixer --get-volume)
mute=$(pamixer --get-mute)


if $mute; then
	icon="󰸈"
else
case 1 in
	$((vol >= 70)) ) icon=" " ;;
	$((vol >= 20)) ) icon="󰕾 " ;;
	$((vol >= 0)) )  icon=" " ;;
	* ) echo undefined&& exit ;;
esac
fi

echo "$icon $vol%"
